LIBS  = $(TELEPATHY_DOCS_LIBS)

all_includes =  $(TELEPATHY_DOCS_CFLAGS) $(TELEPATHY_DOCS_WARNING_FLAGS)

DEFS = @DEFS@
DEFAULT_INCLUDES =
INCLUDES = -I. -I$(srcdir) $(strip $(all_includes))


post-html:
	rsync $(rsync_options) $(example_dirs) $$USER@$(web_host):$(web_path)

